apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: daft-ray
spec:
  replicas: 1
  selector:
    matchLabels: {app: pushgateway}
  template:
    metadata:
      labels: {app: pushgateway}
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.11.1
          ports:
            - containerPort: 9091
              name: web
          resources:
            requests: {cpu: 50m, memory: 64Mi}
            limits: {cpu: 200m, memory: 128Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: daft-ray
spec:
  selector: {app: pushgateway}
  ports:
    - name: web
      port: 9091
      targetPort: web
